tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME/apache-cassandra-4.1.0/bin:$PATH"' >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl https://katapod-file-store.s3.us-west-1.amazonaws.com/ds201/lab06-environment.tar.gz \
        --output environment.tar.gz
      tar xf environment.tar.gz
      cassandra
    init: |
    command: | 
      clear
github:
  prebuilds:
    main: true
ports:
  - port: 1-9999
    onOpen: ignore
vscode:
   extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix
image: gitpod/workspace-full:2023-02-27-14-39-56